### ISSUE TITLE
Unsupported use cases

### ISSUE THREAD

**Issue by qb20nh** [rycont/josa-complete#12]
Quick read on [한국어의 조사 - 나무위키]([Web Archive]) reveals that following uses are not yet supported.

- [x] 야/아: 친구야/녀석아, 여/이여: 그대여/사랑이여
- [x] (이)나: 이것이나/저거나
- [x] (이)다: 밥이다/고기다, 이었다/였다: 떡이었다/채소였다
- [x] (이)든: 이것이든/저거든
- [x] (이)라고: “…했군.”이라고/“…했다.”라고
- [x] (이)란: 마늘이란/파란
- [x] (이)랑: 준식이랑/혜리랑
- [x] (이)야: 이것이야/저거야
- [x] (이)며: 산이며/바다며

[한국어의 조사 - 나무위키]: https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%96%B4%EC%9D%98%20%EC%A1%B0%EC%82%AC?rev=377
[Web Archive]: https://web.archive.org/web/20220513161029/https://namu.wiki/w/%ED%95%9C%EA%B5%AD%EC%96%B4%EC%9D%98%20%EC%A1%B0%EC%82%AC?rev=377

**Comment by rycont** [comment]
웹서비스에 들어오는 사용자 입력과 올바르게 매칭되는 프롬프트를 만드는 것이 본 라이브러리를 만든 목적이였저서, 웹서비스에 자주 사용되는 형식만을 우선적으로 구현하였습니다. 따라서 한국어 조사의 일부만 구현이 되어있는데요, 본문에 제시된 조사들도 곧 추가해두겠습니다. 본 라이브러리에 관심을 가져주셔서 고맙습니다 🙏

**Comment by qb20nh** [comment]
Need to ignore punctuations and parenthesis with nesting level
